#include <bits/stdc++.h>
using namespace std;

int main() {
    int t;
    cin >> t;

    while (t--) {
        int n;
        cin >> n;

        int a[101], cnt[101] = {};

        for (int i = 1; i <= n; i++) {
            cin >> a[i];
            cnt[a[i]]++;
        }

        for (int i = 1; i <= n; i++) {
            for (int j = 100; j >= 1; j--) {
                if (cnt[j] >= i) {
                    cout << j << " ";
                }
            }
        }

        cout << '\n';
    }

    return 0;
}